Create basic Utopia+Swoole demo
utopia-php/demo pull request #1
Opened 2021-03-11 20:38 UTC by kodumbeats

First draft of the Utopia+Swoole basic demo.

2021-03-11 20:41 UTC, eldadfux approved these changes

2021-03-11 20:46 UTC, eldadfux requested changes
+ A minimal Travis test can be nice :)

2021-03-11 20:46 UTC, eldadfux commented on docker-compose.yml
> +    command: app/server.php
We can add this command directly in the dockerfile

2021-03-11 20:46 UTC, eldadfux commented on Dockerfile
> +FROM php:7.4.2-cli
An Alpine example might be more beneficial as this is our default choice.

2021-03-11 20:46 UTC, eldadfux commented on Dockerfile
> +RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64
Not sure why we need this.

2021-03-11 20:46 UTC, eldadfux commented on README.md
> +git clone https://github.com/kodumbeats/utopiademo
Update the URL

2021-03-11 20:46 UTC, eldadfux commented on README.md
> +composer install
We can have the composer install as part of the first stage of build, same as we do in the Appwrite dockerfile.

2021-03-11 21:36 UTC, kodumbeats commented
The refactor should address all of your comments. I'll add a Travis test and re-request your review :)

2021-03-12 11:03 UTC, eldadfux approved these changes

2021-03-12 11:03 UTC, merged

2021-03-12 11:03 UTC, eldadfux commented
🤘