Feat: Add CodeQL Analyzer
utopia-php/demo pull request #11
Opened 2022-10-12 03:08 UTC by thinkverse

This PR adds PHPStan to analyze the demo app for code quality. While not strictly needed in a demo app, it does show a user looking through the demo how to add it to their project. 👍

Closes https://github.com/appwrite/appwrite/issues/4378

2022-10-12 07:10 UTC, Meldiron commented
@thinkverse , thanks for the PR! 🤯 Please give us some time to review it.

2022-10-12 16:26 UTC, christyjacob4 approved these changes
PR looks good 👍  Will wait for reviews from @Meldiron

2022-10-12 16:29 UTC, christyjacob4 commented on .github/workflows/codeql-analysis.yml
> +        "composer install --profile --ignore-platform-reqs && composer check
```suggestion
        "composer install --profile --ignore-platform-reqs && composer check"
```

You're missing the double quotes which is preventing the check from running

2022-10-12 16:29 UTC, christyjacob4 requested changes
Please address the comments

2022-10-12 16:31 UTC, thinkverse commented
> Please address the comments

Done and done. 👍

2022-10-31 16:31 UTC, Meldiron commented
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

2022-11-17 05:19 UTC, stnguyen90 requested changes
Great PR! 🤯 Please make sure to:

1. update the composer.json to include the check script 
2. run the check and fix any problems

2022-11-17 05:23 UTC, thinkverse commented
> 1. update the composer.json to include the check script

Great catch, seems when I merged in the latest from main (https://github.com/utopia-php/demo/pull/11/commits/a3023e3e7c8b936c574114854ce8360530e78ffd) the check script I had added before got removed. 😂

2022-11-17 06:05 UTC, thinkverse commented
If someone could take care of the comment block above `App::init()` later since it doesn't match anymore that would be great. 👍 Appwrite team members will be able to re-write the comment with a proper explanation.

2022-11-17 06:09 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2022-12-21 14:49 UTC, thinkverse commented
OK, now this PR has been fixed of the conflict error caused by the latest merge into `main`, fixed some PHP version issues since the demo isn't locked to a specific PHP version. 👍

2022-12-22 19:17 UTC, stnguyen90 approved these changes
Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

2023-01-09 14:33 UTC, christyjacob4 approved these changes

2023-01-09 14:33 UTC, merged

2023-01-09 14:33 UTC, christyjacob4 commented
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)